# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 544e83c0b8d1d58d609067f1ad636e5903d83046cfc6f672ad7458a2492be3e094852c6080593e3705eb06279f05bbd115e5014269496a6d5afe597c8051acb3

test:
  secret_key_base: 9a5fec155828c9186510b656216e33924227e4c4936e1ed10712acfa9b5b3b9a0af63bc99dfb8f406a7abc00832924a47d488d7a340f0f01b9d03f0a37f4ac80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
